version: '2.0'

services:
  $FQDN:
    image: onedata/onezone:17.06.0-rc2
    container_name: onezone-1
    hostname: $FQDN
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
   #   - "/volumes/persistence:/volumes/persistence"
      # Certificates
   #   - "/volumes/letsencrypt/etc/live/datahub.egi.eu/privkey.pem:/etc/oz_panel/certs/key.pem"
   #   - "/volumes/letsencrypt/etc/live/datahub.egi.eu/cert.pem:/etc/oz_panel/certs/cert.pem"
   #   - "/volumes/letsencrypt/etc/live/datahub.egi.eu/chain.pem:/etc/oz_panel/certs/cert.pem"
   #  - "/volumes/letsencrypt/etc/live/datahub.egi.eu/chain.pem:/etc/oz_worker/cacerts/cacert.pem"
      # Configs
    #  - "/volumes/configs/oz_worker/auth.config:/var/lib/oz_worker/auth.config"
    #  - "/volumes/configs/oz_worker/dns.config:/var/lib/oz_worker/dns.config"
      # Utils
   #   - "/volumes/configs/oz_worker/brand-logo.svg:/var/lib/oz_worker/gui_static/assets/images/brand-logo.svg"
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "80:80"
      - "5555:5555"
      - "5556:5556"
      - "6665:6665"
      - "6666:6666"
      - "7443:7443"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    extra_hosts:
      - "$FQDN:127.0.0.1"
      - "onedata00.cloud.plgrid.pl:10.6.224.168"
      - "onedata01.cloud.plgrid.pl:10.6.224.169"
      - "zonedb01.cloud.plgrid.pl:10.6.224.187"
      - "zonedb02.cloud.plgrid.pl:10.6.224.189"
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_LOG_LEVEL: "info"
      ONEPANEL_BATCH_MODE: "true"
      ONEZONE_CONFIG: |
        cluster:
          domainName: "$DOMAIN_NAME"
          autoDeploy: true
          nodes:
            n1:
              hostname: "onedata00"
            n2:
              hostname: "onedata01"
            n3:
              hostname: "zonedb01"
            n4:
              hostname: "zonedb02"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
              - "n2"
          workers:
            nodes:
              - "n1"
              - "n2"
          databases:
            serverQuota: 2048
            bucketQuota: 1433
            nodes:
              - "n1"
              - "n3"
              - "n4"
        onezone:
          name: "EGI DATAHUB"
          domainName: "$DOMAIN_NAME"
        onepanel:
          users:
            "admin":
              password: "${ADMIN_PASSWORD}"
              userRole: "admin"
            "ldutka":
              password: "${LDUTKA_PASSWORD}"
              userRole: "admin"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400