version: '2.0'

services:
  doc:
    image: docker.onedata.org/onedata-documentation:ID-fe65d545aa
    environment:
      ONEDATA_DOC_VERSION:
    volumes:
      - /usr/share/nginx/html

  nginx:
    restart: always
    image: nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - doc
    ports:
      - "8080:80"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
