version: '2.0'

services:
  doc:
    image: docker.onedata.org/onedata-documentation:678a5aaf00f98e630bbf18dde1dd157882b17e85
    environment:
      ONEDATA_DOC_VERSION:
    volumes:
      - /usr/share/nginx/html

  nginx:
    restart: always
    image: nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - doc
    ports:
      - "8080:80"
