version: '2.0'

services:
  oneclient:
    image: onedata/oneclient:nightly-ID-32e7d74ffa
    privileged: true
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneclient-1
    networks:
      - scenario2
    environment:
      PROVIDER_HOSTNAME: $PROVIDER_HOSTNAME
      ONECLIENT_AUTHORIZATION_TOKEN: $ONECLIENT_AUTHORIZATION_TOKEN
      NO_CHECK_CERTIFICATE: 'true'

networks:
  scenario2:
