version: '2.0'

services:
  node1.onezone.localhost:
    image: docker.onedata.org/onezone:ID-97fad9edf0
    hostname: node1.onezone.localhost
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: onezone-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistance
        - "${ONEZONE_CONFIG_DIR}:/volumes/persistence"
        # OpenId configuration
        #- "${AUTH_PATH}:/var/lib/oz_worker/auth.config"
        # DNS configuration
        #- "${DNS_PATH}:/var/lib/oz_worker/dns.config"
        # Onepanel
        #- "${OZ_PRIV_KEY_PATH}:/etc/oz_panel/certs/key.pem"
        #- "${OZ_CERT_PATH}:/etc/oz_panel/certs/cert.pem"
        #- "${OZ_CACERT_PATH}:/etc/oz_panel/cacerts/cacert.pem"
        #- "${OZ_CACERT_PATH}:/etc/oz_worker/cacerts/cacert.pem"
    networks:
      - scenario2
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_BATCH_MODE: "true"
      ONEZONE_CONFIG: |
        cluster:
          domainName: "onezone.localhost"
          autoDeploy: true
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
        onezone:
          name: "${ZONE_NAME}"
          domainName: "onezone.localhost"
        onepanel:
          users:
            "admin":
              password: "password"
              userRole: "admin"
            "user":
              password: "password"
              userRole: "regular"

networks:
  scenario2:
